#linters-settings:
#  lll:
#    line-length: 140

linters:
  enable:
    - gofmt
    - golint
    - goimports
    #    - stylecheck
    - scopelint
#    - lll

run:
  skip-dirs:
    - test/
    - out/
  skip-files:
    - "zz_.*\\.deepcopy\\.go$"

