#linters-settings:
#  lll:
#    line-length: 140

linters:
  enable:
    - gofmt
    - golint
    - goimports
#    - stylecheck
    - scopelint
#    - lll

run:
  skip-dirs:
    - test/
    - out/

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.15.x # use the fixed version to not introduce new linters unexpectedly

