apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: desired-component-role
rules:
- apiGroups:
  - env.samsahai.io
  resources:
  - desiredcomponents
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - env.samsahai.io
  resources:
  - desiredcomponents/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - env.samsahai.io
  resources:
  - queues
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - env.samsahai.io
  resources:
  - queues/status
  verbs:
  - get
  - update
  - patch
