apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "samsahai.fullname" . }}-staging
  labels:
    {{ include "samsahai.labels" . | indent 4 | trim }}
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - env.samsahai.io
    resources:
      - desiredcomponents
      - queues
      - queuehistories
      - stablecomponents
    verbs:
      - "*"
