apiVersion: v1
kind: Service
metadata:
  name: {{ include "samsahai.fullname" . }}
  labels:
    app.kubernetes.io/component: http
    {{ include "samsahai.labels" . | indent 4 | trim }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "samsahai.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
