apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-helm-operator
spec:
  template:
    spec:
      serviceAccountName: flux-helm-operator
      containers:
        - name: helm-operator
          env:
            - name: http_proxy
              value: $(http_proxy)
            - name: https_proxy
              value: $(https_proxy)
            - name: no_proxy
              value: $(no_proxy)
          volumeMounts:
            - name: git-key
              mountPath: /etc/fluxd/ssh
              readOnly: true
      volumes:
        - name: git-key
          secret:
            secretName: git-key
            defaultMode: 0400